import{a as p,S as y,i as n}from"./assets/vendor-BfjKTZs6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const h="49577891-dd8edba8495efad2486051016",b="https://pixabay.com/api/";async function L(o){return(await p.get(b,{params:{key:h,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data.hits}function S(o){const r=document.querySelector(".gallery"),a=o.map(({webformatURL:e,largeImageURL:t,tags:s,likes:d,views:g,comments:m,downloads:f})=>`
        <li class="gallery-item">
            <a href="${t}" data-lightbox="gallery">
                <img src="${e}" alt="${s}" />
            </a>
            <div class="info">
                <p>Likes: ${d} | Views: ${g} | Comments: ${m} | Downloads: ${f}</p>
            </div>
        </li>
    `).join("");r.innerHTML=a,new y(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const q=document.querySelector(".form"),l=document.querySelector(".gallery"),c=document.querySelector(".loader");let u;q.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(!r){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}l.innerHTML="",console.log("Галерея очищена:",l.innerHTML),c.style.display="block";try{const a=await L(r);a.length===0?n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(S(a),u=new y(".gallery a",{captionsData:"alt",captionDelay:250}),u.refresh())}catch{n.error({title:"Error",message:"Failed to fetch images. Try again later.",position:"topRight"})}finally{c.style.display="none"}});
//# sourceMappingURL=index.js.map
